import matplotlib.pyplot as plt
from data_class import data
import sounddevice as sd
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import (
    QApplication, QWidget, QToolTip, QPushButton, QMessageBox)
import webbrowser


def clicked():
    webbrowser.open_new("https://www.youtube.com/watch?v=dQw4w9WgXcQ")
    
class Ui_MainWindow(object):
    def __init__ (self):
        plt.rc_context(rc={'axes.edgecolor': 'white', 'xtick.color': 'white', 'ytick.color': 'white', 'figure.facecolor': 'white'})
        self.figure = plt.subplots(3)
        self.lst_mesure = []
        self.lst_devices_in = []
        self.lst_devices_out = []
        self.lst_devices = []
        self.lst_test = []

        self.devices = sd.query_devices()

        for device in self.devices:

            if device.get("max_input_channels") == 0:
                self.lst_devices_out.append(device.get("name"))
            elif device.get("max_output_channels") == 0:
                self.lst_devices_in.append(device.get("name"))
            self.lst_devices.append(device.get("name"))
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1129, 881)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 236, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 236, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 236, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 236, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.imageDeutac = QtWidgets.QLabel(self.centralwidget)
        self.imageDeutac.setGeometry(QtCore.QRect(-150, 0, 1281, 121))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 204, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 204, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 204, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 204, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 204, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 204, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 204, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 204, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 204, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.imageDeutac.setPalette(palette)
        self.imageDeutac.setStyleSheet("QLabel#imageDeutac{\n"
"    background-color:rgb(255,204,153);\n"
"    border: 2px solid gray;\n"
"}")
        self.imageDeutac.setText("")
        self.imageDeutac.setPixmap(QtGui.QPixmap("nolaum.png"))
        self.imageDeutac.setObjectName("imageDeutac")
        self.label_generalinfo = QtWidgets.QLabel(self.centralwidget)
        self.label_generalinfo.setGeometry(QtCore.QRect(100, 140, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_generalinfo.setFont(font)
        self.label_generalinfo.setObjectName("label_generalinfo")
        self.label_measurmentdef = QtWidgets.QLabel(self.centralwidget)
        self.label_measurmentdef.setGeometry(QtCore.QRect(100, 360, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_measurmentdef.setFont(font)
        self.label_measurmentdef.setObjectName("label_measurmentdef")
        self.label_aquisition = QtWidgets.QLabel(self.centralwidget)
        self.label_aquisition.setGeometry(QtCore.QRect(670, 140, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell Nova")
        font.setPointSize(14)
        self.label_aquisition.setFont(font)
        self.label_aquisition.setObjectName("label_aquisition")
        self.BG_LeasDef = QtWidgets.QGroupBox(self.centralwidget)
        self.BG_LeasDef.setGeometry(QtCore.QRect(60, 400, 271, 121))
        self.BG_LeasDef.setStyleSheet("QGroupBox#BG_LeasDef{\n"
"    background-color:rgb(255,204,153);\n"
"    border: 2px solid gray;\n"
"}\n"
"")
        self.BG_LeasDef.setTitle("")
        self.BG_LeasDef.setObjectName("BG_LeasDef")
        self.checkBox_2 = QtWidgets.QCheckBox(self.BG_LeasDef)
        self.checkBox_2.setGeometry(QtCore.QRect(40, 70, 162, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.BG_LeasDef)
        self.checkBox_3.setGeometry(QtCore.QRect(40, 30, 193, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName("checkBox_3")
        self.groupBox_Aquisition = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_Aquisition.setGeometry(QtCore.QRect(390, 180, 651, 631))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.groupBox_Aquisition.setPalette(palette)
        self.groupBox_Aquisition.setStyleSheet("QGroupBox#groupBox_Aquisition{\n"
"    border: 2px solid gray;\n"
"}")
        self.groupBox_Aquisition.setTitle("")
        self.groupBox_Aquisition.setObjectName("groupBox_Aquisition")
        self.GB_AquisitionFreqPara = QtWidgets.QGroupBox(self.groupBox_Aquisition)
        self.GB_AquisitionFreqPara.setGeometry(QtCore.QRect(20, 50, 611, 481))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 204, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(96, 99, 99))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(129, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 204, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 204, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 204, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(96, 99, 99))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(129, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 204, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 204, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(96, 99, 99))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 204, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(96, 99, 99))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(129, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(96, 99, 99))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(96, 99, 99))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 204, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 204, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(193, 199, 199))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.GB_AquisitionFreqPara.setPalette(palette)
        self.GB_AquisitionFreqPara.setStyleSheet("QGroupBox#GB_AquisitionFreqPara{\n"
"    background-color:rgb(255,204,153);\n"
"    border: 2px solid gray;\n"
"}")
        self.GB_AquisitionFreqPara.setTitle("")
        self.GB_AquisitionFreqPara.setFlat(False)
        self.GB_AquisitionFreqPara.setCheckable(False)
        self.GB_AquisitionFreqPara.setChecked(False)
        self.GB_AquisitionFreqPara.setObjectName("GB_AquisitionFreqPara")
        self.gridLayout = QtWidgets.QGridLayout(self.GB_AquisitionFreqPara)
        self.gridLayout.setObjectName("gridLayout")
        self.label_minfrq = QtWidgets.QLabel(self.GB_AquisitionFreqPara)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_minfrq.setFont(font)
        self.label_minfrq.setObjectName("label_minfrq")
        self.gridLayout.addWidget(self.label_minfrq, 3, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.GB_AquisitionFreqPara)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 7, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.GB_AquisitionFreqPara)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 7, 1, 1, 1)
        self.label_Chmesure = QtWidgets.QLabel(self.GB_AquisitionFreqPara)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_Chmesure.setFont(font)
        self.label_Chmesure.setObjectName("label_Chmesure")
        self.gridLayout.addWidget(self.label_Chmesure, 12, 0, 1, 1)
        self.label_interfaceIN = QtWidgets.QLabel(self.GB_AquisitionFreqPara)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_interfaceIN.setFont(font)
        self.label_interfaceIN.setObjectName("label_interfaceIN")
        self.gridLayout.addWidget(self.label_interfaceIN, 8, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.GB_AquisitionFreqPara)
        self.lineEdit.setStyleSheet("QlineEdit{\n"
" background-color:rgb(27,27,27);\n"
" border-raduis:12px;\n"
" color:rgb(240,240,240);\n"
" padding-left:15px;\n"
" border: 1px solid rgba(255,255,255, 50);\n"
"}\n"
"QlineEdit:focus{\n"
" border: 1px solid rgba(99,173,229, 150);\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 4, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.GB_AquisitionFreqPara)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.comboBox_2.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout.addWidget(self.comboBox_2, 9, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.GB_AquisitionFreqPara)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.GB_AquisitionFreqPara)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.label_samplerate = QtWidgets.QLabel(self.GB_AquisitionFreqPara)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_samplerate.setFont(font)
        self.label_samplerate.setObjectName("label_samplerate")
        self.gridLayout.addWidget(self.label_samplerate, 6, 1, 1, 1)
        self.label_interfaceOUT = QtWidgets.QLabel(self.GB_AquisitionFreqPara)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_interfaceOUT.setFont(font)
        self.label_interfaceOUT.setObjectName("label_interfaceOUT")
        self.gridLayout.addWidget(self.label_interfaceOUT, 8, 1, 1, 1)
        self.label_delta_F = QtWidgets.QLabel(self.GB_AquisitionFreqPara)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_delta_F.setFont(font)
        self.label_delta_F.setObjectName("label_delta_F")
        self.gridLayout.addWidget(self.label_delta_F, 6, 0, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.GB_AquisitionFreqPara)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.comboBox_4.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.comboBox_4.setFont(font)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.gridLayout.addWidget(self.comboBox_4, 9, 0, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.GB_AquisitionFreqPara)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 13, 0, 1, 1)
        self.label_minfrq_2 = QtWidgets.QLabel(self.GB_AquisitionFreqPara)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_minfrq_2.setFont(font)
        self.label_minfrq_2.setObjectName("label_minfrq_2")
        self.gridLayout.addWidget(self.label_minfrq_2, 0, 0, 1, 1)
        self.label_maxfreq = QtWidgets.QLabel(self.GB_AquisitionFreqPara)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_maxfreq.setFont(font)
        self.label_maxfreq.setObjectName("label_maxfreq")
        self.gridLayout.addWidget(self.label_maxfreq, 3, 1, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.GB_AquisitionFreqPara)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout.addWidget(self.lineEdit_7, 1, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.GB_AquisitionFreqPara)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 4, 1, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.GB_AquisitionFreqPara)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout.addWidget(self.lineEdit_6, 13, 1, 1, 1)
        self.label_Chref = QtWidgets.QLabel(self.GB_AquisitionFreqPara)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_Chref.setFont(font)
        self.label_Chref.setObjectName("label_Chref")
        self.gridLayout.addWidget(self.label_Chref, 12, 1, 1, 1)
        self.label_aquisitionFrequencyParameters = QtWidgets.QLabel(self.groupBox_Aquisition)
        self.label_aquisitionFrequencyParameters.setGeometry(QtCore.QRect(210, 10, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_aquisitionFrequencyParameters.setFont(font)
        self.label_aquisitionFrequencyParameters.setObjectName("label_aquisitionFrequencyParameters")
        self.pushButton_startthemesure = QtWidgets.QPushButton(self.groupBox_Aquisition)
        self.pushButton_startthemesure.setGeometry(QtCore.QRect(230, 550, 191, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.pushButton_startthemesure.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_startthemesure.setFont(font)
        self.pushButton_startthemesure.setObjectName("pushButton_startthemesure")
        self.BG_generalinfo = QtWidgets.QGroupBox(self.centralwidget)
        self.BG_generalinfo.setGeometry(QtCore.QRect(60, 180, 281, 131))
        self.BG_generalinfo.setStyleSheet("QGroupBox#BG_generalinfo{\n"
"    background-color:rgb(255,204,153);\n"
"    border: 2px solid gray;\n"
"}\n"
"")
        self.BG_generalinfo.setTitle("")
        self.BG_generalinfo.setObjectName("BG_generalinfo")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.BG_generalinfo)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_measurmentlabel = QtWidgets.QLabel(self.BG_generalinfo)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(167, 156, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(251, 234, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(209, 195, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(83, 78, 80))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(111, 104, 107))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(167, 156, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 205, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(167, 156, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(251, 234, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(209, 195, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(83, 78, 80))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(111, 104, 107))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(167, 156, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 205, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(83, 78, 80))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(167, 156, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(251, 234, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(209, 195, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(83, 78, 80))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(111, 104, 107))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(83, 78, 80))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(83, 78, 80))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(167, 156, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(167, 156, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(167, 156, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.label_measurmentlabel.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_measurmentlabel.setFont(font)
        self.label_measurmentlabel.setObjectName("label_measurmentlabel")
        self.gridLayout_2.addWidget(self.label_measurmentlabel, 0, 0, 1, 2)
        self.lineEditmeasurmentlabel = QtWidgets.QLineEdit(self.BG_generalinfo)
        self.lineEditmeasurmentlabel.setObjectName("lineEditmeasurmentlabel")
        self.gridLayout_2.addWidget(self.lineEditmeasurmentlabel, 1, 0, 1, 2)
        self.label_author = QtWidgets.QLabel(self.BG_generalinfo)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_author.setFont(font)
        self.label_author.setObjectName("label_author")
        self.gridLayout_2.addWidget(self.label_author, 2, 0, 1, 1)
        self.label_date = QtWidgets.QLabel(self.BG_generalinfo)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_date.setFont(font)
        self.label_date.setObjectName("label_date")
        self.gridLayout_2.addWidget(self.label_date, 2, 1, 1, 1)
        self.lineEdit_author = QtWidgets.QLineEdit(self.BG_generalinfo)
        self.lineEdit_author.setObjectName("lineEdit_author")
        self.gridLayout_2.addWidget(self.lineEdit_author, 3, 0, 1, 1)
        self.lineEdit_date = QtWidgets.QLineEdit(self.BG_generalinfo)
        self.lineEdit_date.setObjectName("lineEdit_date")
        self.gridLayout_2.addWidget(self.lineEdit_date, 3, 1, 1, 1)
        self.pushButton_rickroll = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_rickroll.setGeometry(QtCore.QRect(1102, 0, 31, 21))
        self.pushButton_rickroll.setStyleSheet("QPushButton#pushButton_rickroll{\n"
" background-color:rgb(50,50,50);\n"
"}")
        self.pushButton_rickroll.setText("")
        self.pushButton_rickroll.setObjectName("pushButton_rickroll")
        self.pushButton_rickroll.clicked.connect(clicked)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 570, 271, 221))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1129, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        #self.pushButton_startthemesure.clicked.connect(self.pressed)
        self.pushButton_startthemesure.clicked.connect(self.mesure)
        self.pushButton_3.clicked.connect(self.show)
        self.pushButton_2.clicked.connect(self.clear)
        
        self.checkBox_2.stateChanged.connect(self.trace)
        self.checkBox_3.stateChanged.connect(self.trace)
        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_generalinfo.setText(_translate("MainWindow", "General Informations"))
        self.label_measurmentdef.setText(_translate("MainWindow", "Graphic parametres"))
        self.label_aquisition.setText(_translate("MainWindow", "Aquisition"))
        self.checkBox_2.setText(_translate("MainWindow", "Vertical axes : dB "))
        self.checkBox_3.setText(_translate("MainWindow", "Horizontal axes : LogX"))
        self.label_minfrq.setText(_translate("MainWindow", "Min Frequency (Hz)"))
        self.lineEdit_3.setText(_translate("MainWindow", "1"))
        self.lineEdit_4.setText(_translate("MainWindow", "Not used"))
        self.label_Chmesure.setText(_translate("MainWindow", "Ch mesure"))
        self.label_interfaceIN.setText(_translate("MainWindow", "Interface IN"))
        self.lineEdit.setText(_translate("MainWindow", "50"))
        for i in range(len(self.lst_devices_in)):
            (self.comboBox_4.setItemText(i, _translate("MainWindow",self.lst_devices_in[i])))
        self.comboBox.setItemText(0, _translate("MainWindow", "Chrip"))
        self.comboBox.setItemText(1, _translate("MainWindow", "White Noise"))
        self.label.setText(_translate("MainWindow", "Number of average"))
        self.label_samplerate.setText(_translate("MainWindow", "Sample Rate (Hz)"))
        self.label_interfaceOUT.setText(_translate("MainWindow", "Interface OUT"))
        self.label_delta_F.setText(_translate("MainWindow", "                          Δ f"))
        for i in range(len(self.lst_devices_out)):
            (self.comboBox_2.setItemText(i, _translate("MainWindow",self.lst_devices_out[i]))) 
        self.lineEdit_5.setText(_translate("MainWindow", "0"))
        self.label_minfrq_2.setText(_translate("MainWindow", "Type of Signal"))
        self.label_maxfreq.setText(_translate("MainWindow", "Max Frequency (Hz)"))
        self.lineEdit_7.setText(_translate("MainWindow", "1"))
        self.lineEdit_2.setText(_translate("MainWindow", "5000"))
        self.lineEdit_6.setText(_translate("MainWindow", "1"))
        self.label_Chref.setText(_translate("MainWindow", "Ch reference"))
        self.label_aquisitionFrequencyParameters.setText(_translate("MainWindow", "Aquisition Frequency Parameters"))
        self.pushButton_startthemesure.setText(_translate("MainWindow", "Start the measure"))
        self.label_measurmentlabel.setText(_translate("MainWindow", "Measurement Label"))
        self.lineEditmeasurmentlabel.setText(_translate("MainWindow", "Measurement "))
        self.label_author.setText(_translate("MainWindow", "Author"))
        self.label_date.setText(_translate("MainWindow", "Date"))
        self.lineEdit_author.setText(_translate("MainWindow", "You"))
        self.lineEdit_date.setText(_translate("MainWindow", "19.12.2001"))
        self.pushButton_2.setText(_translate("MainWindow", "Clear"))
        self.pushButton.setText(_translate("MainWindow", "Save the measure"))
        self.pushButton_3.setToolTip(_translate("MainWindow", "<html><head/><body><pre style=\" margin-top:0px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:142.857%; background-color:#ffffff;\"><span style=\" font-family:\'Menlo,Monaco,Consolas,Courier New,monospace\'; font-size:13px; color:#000000; background-color:#ffffff;\">QObject::</span><span style=\" font-family:\'Menlo,Monaco,Consolas,Courier New,monospace\'; font-size:13px; color:#000088; background-color:#ffffff;\">connect</span><span style=\" font-family:\'Menlo,Monaco,Consolas,Courier New,monospace\'; font-size:13px; color:#000000; background-color:#ffffff;\">(closeBtn, SIGNAL(clicked()), qApp, SLOT(quit()));</span></pre></body></html>"))
        self.pushButton_3.setText(_translate("MainWindow", "Exit"))
##########################################################################
#################     START THE MEASURE BUTTON     #######################
##########################################################################
    def pressed(self, MainWindow):
             self.numberofaverage = self.lineEdit_7.text()
             self.minfreq = self.lineEdit.text()
             self.maxfreq=self.lineEdit_2.text()
             self.delta_F=self.lineEdit_3.text()
             self.samplerate=self.lineEdit_4.text()
             self.chmes=self.lineEdit_5.text()
             self.chref=self.lineEdit_6.text()
             self.nomdlamesure=self.lineEditmeasurmentlabel.text()
             self.author=self.lineEdit_author.text()
             self.date=self.lineEdit_date.text()
             self.comboboxIN = self.comboBox_4.currentText()
             self.comboboxOUT = self.comboBox_2.currentText()
             # self.numberofaverage = self.lineEdit_7.text()
             # self.minfreq = self.lineEdit.text()
             # self.maxfreq=self.lineEdit_2.text()
             # self.delta_F=self.lineEdit_3.text()
             # self.samplerate=self.lineEdit_4.text()
             # self.chmes=self.lineEdit_5.text()
             # self.chref=self.lineEdit_6.text()
             # self.nomdlamesure=self.lineEditmeasurmentlabel.text()
             # self.author=self.lineEdit_author.text()
             # self.date=self.lineEdit_date.text()
             # self.comboboxIN = self.comboBox_4.currentText()
             # self.comboboxOUT = self.comboBox_2.currentText()
             # print(self.numberofaverage) 
             # print(self.minfreq)
             # print(self.maxfreq)
             # print(self.delta_F) 
             # print(self.samplerate)
             # print(self.chmes)
             # print(self.chref)
             # print(self.comboboxIN)
             # print(self.comboboxOUT)
             # print(self.nomdlamesure)
             # print(self.author)
             # print(self.date)
##########################################################################
########################     MESSAGE BOX     #############################
##########################################################################
    def show(self):
        msg=QMessageBox()
        msg.setWindowTitle("WARNING")
        msg.setText("WARNING ! ARE YOU SURE ?")
        msg.setIcon(QMessageBox.Warning)
        msg.setStandardButtons(QMessageBox.Close)
        msg.setDefaultButton(QMessageBox.Cancel)
        msg.buttonClicked.connect(self.popupButton)
        x=msg.exec_()    
    def popupButton(self,i):
        MainWindow.close()
        app.quit()
   
    def trace(self):
            
        self.figure[0].set_facecolor('k')
        #On efface les subplots
        for axe in self.figure[1]:
            axe.clear()
            

        self.figure[1][0].set_title("MODULE", color="white")
        self.figure[1][1].set_title("PHASE", color="white")
        self.figure[1][2].set_title("COHERENCE", color="white")
        plt.tight_layout()
                
        for data_object in self.lst_mesure:
            data_object.data_plot()
        
        for axe in self.figure[1]:
            axe.set_facecolor('k')
            axe.legend()
            axe.spines['right'].set_visible(False)
            axe.spines['top'].set_visible(False)
            axe.grid(True, alpha = 0.25)
             
                
            if self.checkBox_3.isChecked():
                axe.set_xscale("log")
            else:
                axe.set_xscale("linear")
        if self.checkBox_2.isChecked():
            self.figure[1][0].set_yscale("log")
        else:
            self.figure[1][0].set_yscale("linear")
        
        plt.show()

    def mesure(self, MainWindow):
        # self.samplerate=self.lineEdit_4.text()
        # self.author=self.lineEdit_author.text()
        # self.date=self.lineEdit_date.text()

        n_average = int(self.lineEdit_7.text())
        self.ch_mesure_val = float(self.lineEdit_5.text())
        self.ch_ref_val = float(self.lineEdit_6.text())
        self.f_min_value = float(self.lineEdit.text())
        self.f_max_value = float(self.lineEdit_2.text())
        self.delta_F_value = float(self.lineEdit_3.text())
        self.name_value = str(self.lineEditmeasurmentlabel.text())
        self.Fs_value = 44100
        self.interface_in = self.comboBox_4.currentText()
        self.interface_out = self.comboBox_2.currentText()
    
        sd.default.device = [self.lst_devices.index(self.interface_in),self.lst_devices.index(self.interface_out)]   

        
        self.lst_mesure.append(data(figure=self.figure, Fs=self.Fs_value, f_min=self.f_min_value, 
                               f_max=self.f_max_value, delta_F=self.delta_F_value, 
                               ch_mesure=self.ch_mesure_val, ch_ref=self.ch_ref_val, 
                               signal_type="chirp", 
                               name=self.name_value, N_average= n_average))
        
        
        self.trace()

        
        
        
    def clear(self):
        for i in self.lst_mesure[::-1]:
            self.lst_mesure.remove(i)
    
        self.trace()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
